---
title: "Test model invariance to log2-transformation of bulk RNA-seq data"
author: "Jaclyn Taroni"
date: 2025
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    df_print: paged
---


## Set up

### Input/output

```{r}
source(here::here("utils/modeling.R"))
source(here::here("utils/convert_gene_names.R"))

# Directories
processed_data_dir <- here::here("processed_data")
singlecell_data_dir <- here::here(processed_data_dir, "single_cell")
smartseq_data_dir <- here::here(singlecell_data_dir, "GSE119926")
tenx_data_dir <- here::here(singlecell_data_dir, "GSE155446")
models_dir <- here::here("models")
plots_dir <- here::here("plots")
plots_data_dir <- file.path(plots_dir, "data")

# Bulk data
bulk_genex_filepath <- file.path(processed_data_dir, "bulk_genex.tsv")
bulk_metadata_filepath <- file.path(processed_data_dir, "bulk_metadata.tsv")

# Pseudobulk data
pseudobulk_metadata_filepath <- file.path(singlecell_data_dir, 
                                          "pseudobulk_metadata.tsv")
smartseq_genex_filepath <- file.path(smartseq_data_dir, 
                                     "GSE119926_pseudobulk_genex.tsv")
tenx_genex_filepath <- file.path(tenx_data_dir, 
                                 "GSE155446_pseudobulk_genex.tsv")

# Pseudobulk results
pseudobulk_results_filepath <- file.path(plots_data_dir,
                                         "pseudobulk_test_predictions.tsv")

# Models
baseline_filepath <- file.path(models_dir, "baseline.rds")

# Baseline results using typical input
baseline_results_filepath <- file.path(plots_data_dir,
                                       "baseline_plots_df.tsv")
```

### Read in data

```{r }
bulk_genex_df <- readr::read_tsv(bulk_genex_filepath, 
                                 progress = FALSE,
                                 show_col_types = FALSE)
bulk_metadata_df <- readr::read_tsv(bulk_metadata_filepath, 
                                    progress = FALSE,
                                    show_col_types = FALSE)
pseudobulk_metadata_df <- readr::read_tsv(pseudobulk_metadata_filepath, 
                                          progress = FALSE,
                                          show_col_types = FALSE)
smartseq_genex_df <- readr::read_tsv(smartseq_genex_filepath, 
                                     progress = FALSE,
                                     show_col_types = FALSE) |>
  tibble::column_to_rownames("gene")
tenx_genex_df <- readr::read_tsv(tenx_genex_filepath, 
                                 progress = FALSE,
                                 show_col_types = FALSE) |>
  tibble::column_to_rownames("gene")
baseline_models <- readr::read_rds(baseline_filepath)

```


```{r}
# We need to pick three models to test that each have a different RNA-seq
# dataset held out -- 8 happens to be the official model
models_to_test <- baseline_models[c(6, 8, 10)]

# Grab the test RNA-seq data from the model object, which has metadata for the
# training and test datasets
heldout_rnaseq_metadata <- models_to_test |>
  purrr::map(\(model)
               model$test_metadata |> dplyr::filter(platform == "RNA-seq") 
             )

# Get the heldout RNA-seq as is (i.e., TPM)
heldout_rnaseq <- heldout_rnaseq_metadata |>
  purrr::map(\(metadata_df) 
                bulk_genex_df[, c("gene", metadata_df |> dplyr::pull(sample_accession))] |>
                  tibble::column_to_rownames("gene")
            )
  
# log2 transform all data
heldout_rnaseq_log <- heldout_rnaseq |>
  purrr::map(\(genex_df)
               log2(genex_df + 1)
            )

# log2 transform pseudobulk RNA-seq data
smartseq_log_df <- log2(smartseq_genex_df + 1)
tenx_log_df <- log2(tenx_genex_df + 1)

# Split up metadata for scRNA-seq data
smartseq_metadata_df <- pseudobulk_metadata_df |>
  dplyr::mutate(sample_accession = title) |>
  dplyr::filter(sample_accession %in% colnames(smartseq_genex_df))
tenx_metadata_df <- pseudobulk_metadata_df |>
  dplyr::filter(sample_accession %in% colnames(tenx_genex_df))

# Reorder log2 transformed samples
smartseq_log_df <- smartseq_log_df[, smartseq_metadata_df$sample_accession]
tenx_log_df <- tenx_log_df[, tenx_metadata_df$sample_accession]
```


```{r}

```



### Function

```{r}
test_rnaseq_prediction <- function(classifier_list, 
                                   genex_df,
                                   metadata_df,
                                   model_types = c("ktsp",
                                                   "rf",
                                                   "lasso",
                                                   "mm2s",
                                                   "medullopackage")) {

  # Labels
  mb_subgroups <- c("G3", "G4", "SHH", "WNT")
  
  # Initialize list to hold results
  results_list <- list()
  
  if ("ktsp" %in% model_types) {
    
    # kTSP (unw)
    results_list$ktsp_unweighted$test_results <- test_ktsp(
      genex_df_test = genex_df,
      metadata_df_test = metadata_df,
      classifier = classifier_list$ktsp_unweighted$classifier,
      labels = mb_subgroups
    )
    
    # Calculate confusion matrix
    results_list$ktsp_unweighted$cm <- calculate_confusion_matrix(
      predicted_labels = results_list$ktsp_unweighted$test_results$predicted_labels_df$predicted_labels,
      true_labels = metadata_df$subgroup,
      labels = mb_subgroups
    )
    
  }
  
  if ("rf" %in% model_types) {
    
    # RF (w)
    results_list$rf_weighted$test_results <- test_rf(
      genex_df_test = genex_df,
      metadata_df_test = metadata_df,
      classifier = classifier_list$rf_weighted$classifier
    )
    
    # Calculate confusion matrix
    results_list$rf_weighted$cm <- calculate_confusion_matrix(
      predicted_labels = results_list$rf_weighted$test_results$predicted_labels_df$predicted_labels,
      true_labels = metadata_df$subgroup,
      labels = mb_subgroups
    )
    
  }
  
  if ("lasso" %in% model_types) {
    
    # LASSO
    results_list$lasso$test_results <- test_lasso(
      genex_df_test = genex_df,
      metadata_df_test = metadata_df,
      classifier = classifier_list$lasso$classifier
    )
    
    # Calculate confusion matrix    
    results_list$lasso$cm <- calculate_confusion_matrix(
      predicted_labels = results_list$lasso$test_results$predicted_labels_df$predicted_labels,
      true_labels = metadata_df$subgroup,
      labels = mb_subgroups
    )
    
  }
  
  if ("mm2s" %in% model_types) {
    
    # MM2S
    results_list$mm2s$test_results <- test_mm2s(
      genex_df_test = genex_df,
      metadata_df_test = metadata_df
    )

    # Calculate confusion matrix    
    results_list$mm2s$cm <- calculate_confusion_matrix(
      predicted_labels = results_list$mm2s$test_results$predicted_labels_df$predicted_labels,
      true_labels = metadata_df$subgroup,
      labels = c("G3", "G4", "NORMAL", "SHH", "WNT")
    )
    
  }
  
  if ("medullopackage" %in% model_types) {
   
    # medulloPackage
    results_list$medullopackage$test_results <- test_medullo(
      genex_df_test = genex_df,
      metadata_df_test = metadata_df,
      # This is false because we will handle whether or not something is 
      # log2 transformed at the input level
      log_transform = FALSE
    )

    # Calculate confusion matrix    
    results_list$medullopackage$cm <-calculate_confusion_matrix(
      predicted_labels = results_list$medullopackage$test_results$predicted_labels_df$predicted_labels,
      true_labels = metadata_df$subgroup,
      labels = mb_subgroups
    )
    
  }
  
  return(results_list)
  
}
```

```{r}
bulk_tpm_results_list <- list()
bulk_log_results_list <- list()
for (single_repeat in 1) { # seq_along(models_to_test)) {
  
  # Only medulloPackage has not been tested on TPM data
  bulk_tpm_results_list[[single_repeat]] <- test_rnaseq_prediction(
    classifier_list = models_to_test[[single_repeat]],
    genex_df = heldout_rnaseq[[single_repeat]],
    metadata_df = heldout_rnaseq_metadata[[single_repeat]],
    model_types = "medullopackage"
  )
  
  # Other classifiers did not get tested on log2-transformed data
  bulk_log_results_list[[single_repeat]] <- test_rnaseq_prediction(
    classifier_list = models_to_test[[single_repeat]],
    genex_df = heldout_rnaseq_log[[single_repeat]],
    metadata_df = heldout_rnaseq_metadata[[single_repeat]],
    model_types = c("rf", "ktsp", "lasso", "mm2s")
  )
}

```

```{r}
# Smart-seq2 pseudobulk log transformed with models that didn't accept log 
# transformed data
smartseq_log_result <- test_rnaseq_prediction(
  classifier_list = models_to_test[[2]],  # official model
  genex_df = smartseq_log_df,
  metadata_df = smartseq_metadata_df,
  model_types = c("rf", "ktsp", "mm2s")
)

# Medullopackage and MM2S on data that has not been transformed
smartseq_tpm_result <- test_rnaseq_prediction(
  classifier_list = models_to_test[[2]],  # official model
  genex_df = smartseq_genex_df,
  metadata_df = smartseq_metadata_df,
  model_types = c("mm2s", "medullopackage")
)

# 10x pseudobulk log transformed with models that didn't accept log transformed
# data
tenx_log_result <- test_rnaseq_prediction(
  classifier_list = models_to_test[[2]],  # official model
  genex_df = tenx_log_df,
  metadata_df = tenx_metadata_df,
  model_types = c("rf", "ktsp", "mm2s")
)

# Medullopackage and MM2S on 10X count data
tenx_count_result <- test_rnaseq_prediction(
  classifier_list = models_to_test[[2]],  # official model
  genex_df = tenx_genex_df,
  metadata_df = tenx_metadata_df,
  model_types = c("mm2s", "medullopackage")
)
```


```{r}

```



## Session Info

```{r}
sessionInfo()
```

