name: medulloblastoma-classifier
channels:
  - conda-forge
dependencies:
  - python=3.11
  - awscli>=2.15
  - conda-lock>=2.5
  - pre-commit>=3.6
  - jq>=1.7
  - dvc>=2.36.0
  - dvc-s3>=2.18.0
platforms:
  - linux-64
  - osx-64
  - osx-arm64
