name: Build and Push Docker image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Only build if the workflow, Dockerfile, renv.lock, or conda files are modified
on:
  push:
    branches:
      - main
    paths:
        - Dockerfile
        - renv.lock
        - environment.yml
        - conda-lock.yml
        - .github/workflows/build-and-push-docker.yaml
  pull_request:
    branches:
      - main
    paths:
        - Dockerfile
        - renv.lock
        - environment.yml
        - conda-lock.yml
        - .github/workflows/build-and-push-docker.yaml
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # set up Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Set up Docker metadata
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/AlexsLemonade/medulloblastoma-classifier
          tags: type=raw,value=latest

      # Build Docker image and push to GHCR when event is push or manually triggered
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
